### PR TITLE
Ported types.py, with tests

### PR DESCRIPTION
**Pull request by gvidon**
Some date string parse by python library may not be parsed by js ```Date()```.

### CODE REVIEW

**Comment by rgrp** [comment]
I am not planning to review item by item as pretty big but I'm assuming tests are passing. A more useful commit message might be useful given size of PR ;-)

Aside: perhaps we want to add travis support (?) (if so, let's open an issue to track it!)

**Comment by rgrp** [comment]
@pwalsh do you want to review and merge?

**Comment by rgrp** [comment]
Actually I'll just have a go now.

@pwalsh perhaps you want to clarify whether you are planning to review these or ...

**Comment by pwalsh** [comment]
@rgrp Yes, I'm reviewing. You're right about travis, I'll get that setup tomorrow.

**Comment by gvidon** [comment]
Sorry for short PR message, was really in hurry to get to date with other stuff

**Pull request merged**
